---
# Set Hostname
custom_hostname: pop-os-dx

vars_files:
  - vars/apt_packages.yml
  - vars/bash_aliases.yml
  - vars/vscode_extensions.yml
  - vars/starship_vars.yml

install:
  apt_packages: false
  vscode: false
  bitwarden: false
  obsidian: false
  neovim: false
  docker: false
  insomnia: false
  aliases: false
  github: false
  chrome: false
  lazydocker: false
  python: false
  java: false
  npm: false
  go: false
  fonts: false
  starship: false
  intellij: false
  devpod: false
  terraform: false
  gitleaks: false
  zellij: true
  kubectl: false
  kustomize: true
  talosctl: true
  k9s: true
  argocd_cli: true
