- name: Install ArgoCD CLI
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_cli_version }}/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: "0755"
  become: true