- name: Install K9s
  ansible.builtin.unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
  args:
    creates: "/usr/local/bin/k9s"
  become: true