- name: Install Kustomize
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v{{kustomize_version}}/kustomize_v{{kustomize_version}}_linux_amd64.tar.gz" 
    dest: /usr/local/bin/
    remote_src: true
  become: true
  args:
    creates: "/usr/local/bin/kustomize"

- name: Ensure Kustomize is executable
  ansible.builtin.file:
    path: /usr/local/bin/kustomize
    mode: "0755"