- name: Install Talosctl
  ansible.builtin.get_url:
    url: "https://github.com/siderolabs/talos/releases/download/v{{ talosctl_version }}/talosctl-linux-amd64"
    dest: /usr/local/bin/talosctl
    mode: "0755"
  become: true